### ISSUE TITLE
Using this package in 2.0 version

### ISSUE THREAD

**Issue by biladina** [yii2-extensions/debug#15]
### What steps will reproduce the problem?
- clone [this repo](https://github.com/yii2-extensions/app-basic)
- change `"yiisoft/yii2": "^2.2"` to `"yiisoft/yii2": "~2.0.49"`
- run `composer update`

its seems not possible using this package in yii2 version 2.0.*

### What is the expected result?
working, both on installation and using the debug bar

### What do you get instead?
error when install this package using yii2 version 2.0.*

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires yii2-extensions/bootstrap5 dev-main -> satisfiable by yii2-extensions/bootstrap5[dev-main].
    - yii2-extensions/bootstrap5 dev-main requires yiisoft/yii2 ^2.2 -> found yiisoft/yii2[2.2.x-dev] but it conflicts with your root composer.json require (~2.0.49).
  Problem 2
    - Root composer.json requires yii2-extensions/debug dev-main -> satisfiable by yii2-extensions/debug[dev-main].
    - yii2-extensions/debug dev-main requires yiisoft/yii2 ^2.2 -> found yiisoft/yii2[2.2.x-dev] but it conflicts with your root composer.json require (~2.0.49).
  Problem 3
    - Root composer.json requires yii2-extensions/gii dev-main -> satisfiable by yii2-extensions/gii[dev-main].
    - yii2-extensions/gii dev-main requires yiisoft/yii2 ^2.2 -> found yiisoft/yii2[2.2.x-dev] but it conflicts with your root composer.json require (~2.0.49).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.1
| Operating system | Main OS is Fedora 38, but I run this app from [yii3 docker image](https://github.com/yiisoft/yii-docker) and [httpd docker image](https://hub.docker.com/_/httpd)

**Comment by terabytesoftw** [comment]
Please take care of your composer.json for me.

**Comment by biladina** [comment]
this my `composer.json`

I just change yii2 package from `2.2` to `2.0.49`

```
{
    "name": "yii2-extensions/app-basic",
    "type": "project",
    "description": "Web Application Basic",
    "keywords": [
        "application",
        "basic",
        "web",
        "yii2"
    ],
    "license": "mit",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=8.1",
        "npm-asset/flag-icons": "^6.1",
        "npm-asset/fortawesome--fontawesome-free": "^6.4",
        "oomphinc/composer-installers-extender": "^2.0",
        "php-forge/awesome-component": "dev-main",
        "php-forge/html": "dev-main",
        "sjaakp/yii2-icon": "^1.0",
        "yii2-extensions/asset-bootstrap5": "dev-main",
        "yii2-extensions/bootstrap5": "dev-main",
        "yii2-extensions/localeurls": "dev-main",
        "yiisoft/config": "^1.4",
        "yiisoft/yii2": "~2.0.49",
        "yiisoft/yii2-symfonymailer": "^3.0"
    },
    "require-dev": {
        "codeception/c3": "^2.8",
        "codeception/codeception": "^5.0.0",
        "codeception/lib-innerbrowser": "^4.0",
        "codeception/module-asserts": "^3.0",
        "codeception/module-filesystem": "^3.0",
        "codeception/module-yii2": "^1.1",
        "codeception/verify": "^3.0",
        "maglnet/composer-require-checker": "^4.6",
        "symfony/browser-kit": "^6.3",
        "symfony/process": "^6.3",
        "yii2-extensions/debug": "dev-main",
        "yii2-extensions/gii": "dev-main",
        "yii2-extensions/phpstan": "dev-main"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        },
        "config-plugin-file": "/config/config-plugin.php",
        "installer-types": [
            "bower-asset",
            "npm-asset"
        ],
        "installer-paths": {
            "./node_modules/{$name}/": [
                "type:bower-asset",
                "type:npm-asset"
            ]
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ],
    "config": {
        "allow-plugins": {
            "codeception/c3": true,
            "yiisoft/yii2-composer": true,
            "composer/installers": true,
            "oomphinc/composer-installers-extender": true,
            "yiisoft/config": true
        }
    }
}
```

**Comment by biladina** [comment]
> ### What steps will reproduce the problem?
> 
>     * clone [this repo](https://github.com/yii2-extensions/app-basic)
> 
>     * change `"yiisoft/yii2": "^2.2"` to `"yiisoft/yii2": "~2.0.49"`
> 
>     * run `composer update`
> 
> 
> its seems not possible using this package in yii2 version 2.0.*
> ### What is the expected result?
> 
> working, both on installation and using the debug bar
> ### What do you get instead?
> 
> error when install this package using yii2 version 2.0.*
> 
> ```
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires yii2-extensions/bootstrap5 dev-main -> satisfiable by yii2-extensions/bootstrap5[dev-main].
>     - yii2-extensions/bootstrap5 dev-main requires yiisoft/yii2 ^2.2 -> found yiisoft/yii2[2.2.x-dev] but it conflicts with your root composer.json require (~2.0.49).
>   Problem 2
>     - Root composer.json requires yii2-extensions/debug dev-main -> satisfiable by yii2-extensions/debug[dev-main].
>     - yii2-extensions/debug dev-main requires yiisoft/yii2 ^2.2 -> found yiisoft/yii2[2.2.x-dev] but it conflicts with your root composer.json require (~2.0.49).
>   Problem 3
>     - Root composer.json requires yii2-extensions/gii dev-main -> satisfiable by yii2-extensions/gii[dev-main].
>     - yii2-extensions/gii dev-main requires yiisoft/yii2 ^2.2 -> found yiisoft/yii2[2.2.x-dev] but it conflicts with your root composer.json require (~2.0.49).
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> ```
> 
> ### Additional info
> Q 	A
> Version 	1.0.?
> PHP version 	8.1
> Operating system 	Main OS is Fedora 38, but I run this app from [yii3 docker image](https://github.com/yiisoft/yii-docker) and [httpd docker image](https://hub.docker.com/_/httpd)

sorry, forget the steps reproduce problem, comment updated..

**Comment by biladina** [comment]
thank you, it works now..
